root: true

env:
  node: true
  browser: true

extends:
  - eslint:recommended

parserOptions:
  ecmaVersion: 12

rules:
  semi: error
  indent: [error, 2]
  quotes: [error, double]
  no-console: off
  import/extensions: off
